# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Node.js image as a parent image
FROM node:18-alpine AS build

# Set the working directory in the container to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package.json /app/
COPY tsconfig.json /app/

# Install any needed packages specified in package.json
RUN npm install --ignore-scripts

# Copy the rest of the application source code to the container
COPY src /app/src

# Build the TypeScript files
RUN npm run build

# Use a lighter weight image for running the application
FROM node:18-alpine

# Set the working directory in the container to /app
WORKDIR /app

# Copy the compiled output and dependencies from the build stage
COPY --from=build /app/dist /app/dist
COPY --from=build /app/node_modules /app/node_modules

# Expose port 3456 to the outside world
EXPOSE 3456

# Run the application
CMD ["node", "dist/cli.js"]
